### ISSUE TITLE
Mixed content on Mapbook

### ISSUE THREAD

**Issue by stlim0730** [stlim0730/farmview#12]
One issue is that the web browser will block non-CartoDB iframes if they're served over HTTP, but not HTTPS. Roughly speaking, a secure webpage served over HTTPS (like Farmview) cannot contain elements served over HTTP where the web browser says the mixed content issue occurred. If you want to add non-CartoDB iframe hosted somewhere else on the Mapbook, make sure the host serves it over HTTPS and you add it on the admin panel with https:// url (e.g., <iframe src="https://some.server.com/..." ...).

Also, I found that mapbook.html had a link to a Google Font resources served over HTTP. An easy walkaround is that you omit the protocol part of the whole url (e.g., change http://fonts.google.com/... into //fonts.google.com/...).

**Comment by stlim0730** [comment]
One thing I can never understand is that the non-CartoDB iframe we tested yesterday worked perfectly. I don't know why. Somebody explain...

**Comment by brianashpugh** [comment]
@calo1 this seems like a documentation note rather than an issue. Is there somewhere we can record this then close the issue?

**Comment by calo1** [comment]
You are correct.  I archived and closed.  This is a low priority anyway
