### ISSUE TITLE
Managing datafields (currently query fields)

### ISSUE THREAD

**Issue by stlim0730** [stlim0730/farmview#13]
I've been thinking this project has to more smartly maintain query fields and workflow to manage them for a long time. Adam and I commonly had a good excuse, which the MVP doesn't require all the features we need, to defer the tasks. So, I hard-coded most of the features related to query fields to have simple and limited functionalities.

According to the latest updates on query field requirement document (https://docs.google.com/document/d/1bK6pKhQRQbSd9EzEprI12aMkCbYrvqmiwgYHuaNMz38/edit), the number and the complexity of the query fields the tool should handle have both increased. Now I should say it's the time for the deferred task; query fields should be model-based objects that are better structured and easily configurable to support conditional display, rather than hard-coded.

Also, the model will be renamed into datafield to generally used by query and display (view details) features.

I just finished modeling of query field object. I'll put the data based on the requirement doc and work on the conditional display.

**Comment by calo1** [comment]
To add a note from the meeting on 5/4.  Some Select One and Select Multiple question types have the option of "other" as a value.  If this is the case, the survey prompts a text write in response.  The values are inserted into a new column with _other appended.  The values of this field should not need to be queried.  However, the values should eventually be displayed.  Reserve this challenge for later.

**Comment by calo1** [comment]
Hi @stlim0730, picking this up.  Adding some new query fields based on survey data fields.  Maybe a CS undergrad can take on this modeling task?
