### ISSUE TITLE
Documentation for datafield

### ISSUE THREAD

**Issue by stlim0730** [stlim0730/farmview#15]
What's missing in the datafield documentation (https://docs.google.com/document/d/1bK6pKhQRQbSd9EzEprI12aMkCbYrvqmiwgYHuaNMz38/edit) is the type of each datafield. I made two blank columns in the tables: Type and Choices.

- Type column will have one of the three possible query UI types the application currently support; Text, Range, or Select One
- Choices column will have exact string values that CartoDB dataset has (e.g., welloffsite, part_of_farm_available). Each value is spearated by a new line.
- The only type that requires choices column to be filled is Select One.

When I worked on datafield, I used to go to CartoDB to see what type a column has. As the project needs to handle more objects and higher complexity of the model, the type definition should go into the table.

**Comment by calo1** [comment]
Its about time to make and overhaul of the data schema, including the new library for the values.  We should discuss whether to make complete documentation for the datafields for the queries or for the additional details.

**Comment by calo1** [comment]
For choices column you want the value, but what about a label for the value?

**Comment by stlim0730** [comment]
Labels for the values are what a user sees in a dropbox menu for select one
queries  For example, a user chooses Whole Farm Available rather than
whole_farm_available. The corresponding values go into the query string.

**Comment by calo1** [comment]
I updated the data fields and values

**Comment by stlim0730** [comment]
@calo1, I found disparity between the choice values and choice labels for zone_type. There are 76 values, but 79 labels. I think this is why labels haven't appeared on the detail popup; it should be one-to-one mapping. Please take a close look at the mapping. Once the datafield configuration gets correct, the app will show the labels correctly without any changes of code.

I changed the label into bug and will keep @calo1 as the assignee. Let me know how it goes.

**Comment by calo1** [comment]
@stlim0730  .. it was the escape characters..  Some of the long zone descriptions had quotes and brought on a carriage return.  I attempted to fix it on the admin pane .. but I also Attach a spreadsheet of how it is supposed to be here : https://docs.google.com/a/berkeley.edu/spreadsheets/d/1Vk40U5g6hNFa-bkmEwbhcQ2PUKPcQzRmZ6VrpyNfz3U/edit?usp=sharing

**Comment by stlim0730** [comment]
@calo1 I see the labels are back, but back with the backslash characters followed by double quotes. Do you want me to remove all the escape characters?

**Comment by calo1** [comment]
@stlim0730   for some of the zone fields I was quoting directly from the the zoning authority ...  but they aren't that crucial if they are causing problems

**Comment by stlim0730** [comment]
@calo1 Let me remove them. The fact we see the escape characters means we don't need to escape special characters there. I remember we needed to escape special characters in the earlier version, though.

**Comment by stlim0730** [comment]
@calo1 I removed them all and it looks good. Test the app at your convenience. Let me close this issue unless you find more errors by tonight. Yay!

**Comment by calo1** [comment]
@stlim0730 looking good ... agree.  close by tonight unless errors are found.
