### ISSUE TITLE
Url to map on landing page is incorrect

### ISSUE THREAD

**Issue by calo1** [stlim0730/farmview#3]
When you click "go to map" on the landing page.. you end up in an unrecognized link.  map/ is running, but the button links incorrectly.

Map url:  http://farmview.herokuapp.com/map/

Go to map url: http://farmview.herokuapp.com/map.html

**Comment by bofie123** [comment]
Wait I don't understand.. where does "http://farmview.herokuapp.com/map.html" come from?

**Comment by bofie123** [comment]
ohhh nvm, i know what ur talking about, let me fix it!

**Comment by bofie123** [comment]
should be fixed,but taek needs to deploy for it to show on http://farmview.herokuapp.com/

**Comment by calo1** [comment]
Front end landing page?

**Comment by stlim0730** [comment]
Bofan, I think you now figured out, but I put it here for the record.
The request should be /map, but not /map.html

**Comment by calo1** [comment]
Button on landing page correctly directs to /map
