### ISSUE TITLE
Drop polygonaspoints layer on Carto?

### ISSUE THREAD

**Issue by stlim0730** [stlim0730/farmview#40]
@calo1, if the only purpose of the `polygonaspoints` layer is to define the `data_polygon` layer's behavior in case of specific zoom levels, you can copy css of `polygonaspoints` and append it to css of `data_polygon`. Please drop `polygonaspoints` layer after that. By doing this, `data_polygon` will still have the same behavior of `polygonaspoints` for the specific zoom levels. Trust me.

I'm so happy that this layer will be gone. Yay  x 10,000. I've hated it, but it took so long until I understand why you wanted it and how it has served the purpose.

If the layer has other reasons to exist, let me know before you drop it.

**Comment by calo1** [comment]
@stlim0730  yes ... this layer is problematic.  But it is not just a style layer for the specific zoom layers.  It also uses a  bit of postgresql to create the points in the center of the polygons.  

If I do that same postgres on data_polygon, wont the polygon's disappear? I will have to investigate

**Comment by stlim0730** [comment]
Could you explain more about the postgresql job?

**Comment by calo1** [comment]
to "make"  polygonas points  I called a SELECT St_Centroid(data_polygon.the_geom) to make 1 point at the center of each polygon.  I then made a new layer with this view .. and brought in all of the associated data do that it would be interactable.  Nevertheless, I agree we should rid ourselves this layer.

Maybe I can do this with CSS.

**Comment by stlim0730** [comment]
I understand. What does data_polygon show if you remove polygonaspoints? Doesn't it display the point in the middle of the polygon? I think it does, but am not sure.

If it doesn't, the data_polygon layer can have the same sql statement in the sql panel on Carto. This will do without a new layer, I think.

**Comment by calo1** [comment]
when polygonaspoints is removed, then the points disappear.. whats left are the itty bitty polygons that non one knows are there.

Let me experiment with trying to accomplish the ST_centroid with just data_polygon

**Comment by stlim0730** [comment]
Go ahead. It should work.

**Comment by calo1** [comment]
Ok ..  I did it ... polygon_as_points is disabled  .. but the visualized points are rendered and styled correctly.

**Comment by stlim0730** [comment]
I really want it gone. Remove it!

Thanks, Adam.
As a side note, it's really fun to stealthily do something off the wall at work.
This has been the key reason I could make pretty much improvement in Farmview this summer. I'm enjoying it. Hahahhahahahahhhh

**Comment by calo1** [comment]
Ok. I'm killing the layer .. .  Yay farmview!!!!!!!!! you cant go "off the wall" anytime .. but now your stealth comments are on the public internet, so ...

**Comment by stlim0730** [comment]
The changes you made on Carto will be automatically applied to the app on my local branch and production server as well. No further action needed.

Closing this branch. Cheers!
