### ISSUE TITLE
Maps with "scrollWheelZoom: true" on Mapbook

### ISSUE THREAD

**Issue by stlim0730** [stlim0730/farmview#41]
@calo1, Mapbook has some maps with zooming feature using scroll wheel enabled. All the maps we have edit permission, or authored by Farmview account, should disable this feature.

**Comment by calo1** [comment]
I will destroy this feature on all maps

**Comment by calo1** [comment]
@stlim0730  I only found one map with scroll wheel zoom and I changed it.  Let me know if there are still any TRUE out there

**Comment by calo1** [comment]
Can we close this branch?
