### ISSUE TITLE
LANGUAGES in settings.py is not found for some reason

### ISSUE THREAD

**Issue by nutelIa** [stlim0730/farmview#43]
To make a button to switch between languages, I am trying to use forms that go through available languages, which I have as

`LANGUAGES = [
  ('en', _('English')),
  ('es', _('Spanish')),
]`
in settings.py

I use `{% get_language_info_list for LANGUAGES as languages %}` in the html, but the dropdown menu does not show anything.
I cannot translate to a language that django does not acknowledge the existence of.

**Comment by stlim0730** [comment]
@nutelIa, I think what bothers you is a syntax error.

I think you followed the example on Django documentation. Great. The example imports `ugetext` module from `django.utils.translation` and makes an alias of `ugetext` as `_`. Making alias is not necessary, though. So, `_('English')` and `_('Spanish')` must be identical to `ugetext('English')` and `ugetext('Spanish')`.

I didn't see the import statement in your `settings.py` and I think this causes the problem.

The fix:
```
# At the top of settings.py
import django.utils.translation import ugetext as _

#...

LANGUAGES = [
  ('es', _('Spanish')),
  ('en-us', _('English')),
]
```

It should do the job, or you can move forward at least.
Hope it helps. Let me know how it goes!

**Comment by calo1** [comment]
@nutelIa Hey Natalia, any progress on this?  Are you finding success with Taek's suggestions?

**Comment by calo1** [comment]
@nutelIa ... close this if this issue is done for
