### ISSUE TITLE
Logging for data collection

### ISSUE THREAD

**Issue by stlim0730** [stlim0730/farmview#49]
I think queries that users generate (especially in the workshop) might be a valuable datasource that informs what the users are interested in. For later analysis, we need to save the queries, if possible.

This also reminds me of short conversation with @calo1 about usage-analysis. Google analytics might be a good addition at this moment.

So, this issue includes two-fold analytics methods: a SQL logging feature and Google Analytics integration.

**Comment by calo1** [comment]
I agree .. also data downloads from the mapbook.  But with regards to queries ... Soon we should get back to admin defined queries .. the query fields that are there now are a limited set.  This would make the analytics more profound.

**Comment by stlim0730** [comment]
Done and merged.

Using a 30-day free-trial account of [loggly](https://www.loggly.com/), Farmview logs all the query-related events on the map: infowindow, detail popup, and query UI below the map.

It's just a short-term measure with no cost, easy to integrate, and full-featured. We may want to find better long term solutions.

**Comment by stlim0730** [comment]
I see @calo1's IP starting with 169.233.X.X, which verifies this feature.
If I come up with anything publishable out of this project, I guess it will stem from what I learned from this query log. Unfortunately, every sort of technical effort we made so hard into this app is nothing new. It's a common set of existing knowledge and techniques.

**Comment by calo1** [comment]
If it ain't broke, don't fix it

**Comment by calo1** [comment]
What new tools would you like to build for this project?
