### ISSUE TITLE
formatting on contact us page

### ISSUE THREAD

**Issue by calo1** [stlim0730/farmview#56]
images is all garbled.  needs a small fix and looks like a merge conflict

Should be Contributors instead of Who we are
<img width="936" alt="screen shot 2016-07-25 at 8 48 29 pm" src="https://cloud.githubusercontent.com/assets/8172009/17125547/3b97f544-52a9-11e6-8d20-5e1bedc5ab10.png">

**Comment by stlim0730** [comment]
Should be a simple merge conflict. Don't work off on master, though. LOL

**Comment by stlim0730** [comment]
Currently, I still see "Who We Are", but the merge conflict message is gone.

**Comment by calo1** [comment]
Ok!  I'll edit the content text  via a small content branch and make a pull request
