### ISSUE TITLE
TEMPLATE_* settings were deprecated

### ISSUE THREAD

**Issue by stlim0730** [stlim0730/farmview#58]
Since Farmview's official Django version is 1.9, the deprecated settings should be configured. The Django server shows this warning when it starts.

> ?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_CONTEXT_PROCESSORS.

As a warning not an error, this can be done after the workshop. It's still good to start taking a look relevant documentation, though.

**Comment by nutelIa** [comment]
I fixed this in the minorChanges branch.

**Comment by stlim0730** [comment]
@nutelIa, great!
