### ISSUE TITLE
Map Application should have Carto.js functions: layer selector and address search box

### ISSUE THREAD

**Issue by calo1** [stlim0730/farmview#61]

**Comment by stlim0730** [comment]
Done.

Farmview renders a searchbox powered by Carto.
Farmview _mimics_ the layer selector of Carto. Same look, same behavior in general. The only difference is that if you click the map while the dropdown is open, the dropdown closes on Carto. We don't have this minor feature. It still toggles if you click the layer selector itself.

No serious test is needed, I think. Will close this issue after merge and deploy.
