### ISSUE TITLE
A bug reported by @calo1

### ISSUE THREAD

**Issue by stlim0730** [stlim0730/farmview#66]
/map doesn't render anything after making changes on Carto.
@calo1, let's talk on issues, not PRs. Did you try http? What changes did you make?

**Comment by calo1** [comment]
@stlim0730 currently no bug.

I established he sync link with api_process.  I removed the old tables and replaced the CSS.

CARTO's default new layer settings is "private"  I bet that prevented farmview from reading anything

I changed the layers to "public" now rendering

**Comment by calo1** [comment]
For future reference:  I would like to test layer privacy to "with the link" and see if farmview can read the data...


ALSO it may have just been a temporary vacancy as I delete delete and re-upload data

**Comment by calo1** [comment]
For the conference should users use HTTP or HTTPS?

**Comment by stlim0730** [comment]
Yes, http (#46).
Private can't work with any apps anyway. Protected (only with link) or public will work to my knowledge, if Carto hasn't change the policy.

So, it wasn't a bug. I'll close it.

**Comment by calo1** [comment]
Close it ... Sorry I freaked out!

I think , for survey data : with the link is ideal

**Comment by stlim0730** [comment]
With the link is ideal; agreed!
