### ISSUE TITLE
Data polygon doesn't appear

### ISSUE THREAD

**Issue by stlim0730** [stlim0730/farmview#70]
I suppose that when data_polygon_temp is removed, data_polygon's CSS has gone together. Data is handed from Carto to Farmview, but it doesn't appear on the map.

@calo1, could you check on Carto?

**Comment by calo1** [comment]
OK, good catch.  The CSS was still referencing data_polygon_temp

I think I resolved the issue, but to be honest, my CSS could use review

**Comment by stlim0730** [comment]
Got the css back.
Feels like legit one-day-before demo with all the issues.
