### ISSUE TITLE
Map not rendering on chromebooks.. help!

### ISSUE THREAD

**Issue by calo1** [stlim0730/farmview#72]
@stlim0730 Everything else on farmview is working however. renders fine on my mapbook

**Comment by stlim0730** [comment]
http?

**Comment by calo1** [comment]
Actually, 2 out of 5 are working ...

**Comment by stlim0730** [comment]
Check the versions of Chrome and update

**Comment by calo1** [comment]
updating the non working ones.

**Comment by calo1** [comment]
OK, updating did it ... The ones I tested last night were randomly updated
