### ISSUE TITLE
Base Map changes

### ISSUE THREAD

**Issue by calo1** [stlim0730/farmview#76]
I believe @stlim0730 changed the process so now mapbox is creating the basemap instead of Carto.

Eventually, A user should be able to change the basemap,

For now I like 
Mpabox outdoors 

https://api.mapbox.com/styles/v1/mapbox/outdoors-v9.html?title=true&access_token=pk.eyJ1IjoidGF0aWFuYSIsImEiOiJjaWs1bzRiZGQwMDdjcHRrc285bTdwcWU5In0.0EWPVHyjaE9jTzNvOiIO-w#14.19/36.9835/-121.8895

or Mapbox satellite streets

https://api.mapbox.com/styles/v1/mapbox/satellite-streets-v9.html?title=true&access_token=pk.eyJ1IjoidGF0aWFuYSIsImEiOiJjaWs1bzRiZGQwMDdjcHRrc285bTdwcWU5In0.0EWPVHyjaE9jTzNvOiIO-w#12.54/36.6216/-121.5425

**Comment by stlim0730** [comment]
No, since it's the era of data-driven app rendering, the basemap settings also follow Carto data.

Configurable basemap is still possible, but I'd put it at the lowest priority unless you have difficulty in seeing anything on the map.

**Comment by calo1** [comment]
I'm testing out a carto satellite basemap for a while

**Comment by calo1** [comment]
The carto basemaps are working for now. lets just leave this for now.
