### ISSUE TITLE
Refactoring 1: Repository management

### ISSUE THREAD

**Issue by stlim0730** [stlim0730/farmview#77]
Being on the same page is the most important thing in collaboration. This issue is about making our local repos be on the same page from now on.

1. If you have any local changes (compared to current `master`), make copies of the files you've changed in a separate location. If you don't have any, skip this step.

2. Remove your local repo.

3. Clone the remote repo. This will include all the latest updates.

This is it for the local repo. Now for you:

1. Don't use `git add .` or `git add *.*`.
    - When you add files that have been tracked (or existing files in the repo), use `git add -u`. It's simple enough to add all the files with just ten letters of command. No wild card characters at all.

      > -u
      > --update
      > Update the index just where it already has an entry matching <pathspec>. This removes as well as modifies index entries to match the working tree, but adds no new files.
      > 
      > If no <pathspec> is given when -u option is used, all tracked files in the entire working tree are updated (old versions of Git used to limit the update to the current directory and its subdirectories).
      > https://git-scm.com/docs/git-add

    - When you add files you just created (or new files), use your extreme discernment rather than `git add *.*`.
        * You can always _specify_ multiple files that really need to be added using wild card characters. For example, `git add *.py` is much more _specific_ than `git add .`.
2. Don't add files (especially, binaries) that are not necessary.
    - One of the biggest reason I encouraged you to clone the repo again is to share `.gitignore`, which specifies what files we avoid to add into the repo (I recommend you take a look at the file).
    - Every single file in the repo must have a good reason to be added.
3. If two or more people are remotely working on the same branch, pay attention to what files they are working on.
    - You can do this on Github by navigating commits on the branch.
    - Another way of doing this is to browse the history of the file of your interest on Github. Make sure you're on the right branch.
4. Commit often, with good names.
    - Obviously.
5. Conflict first
    - We haven't experienced serious merge conflicts yet, which is great. If we have one, we'll stop everything until we resolve it.
6. Django-specific rule: `.py` files in `migration` are very important.
    - They have database manipulation codes that automatizes model changes. If you lose them, you lose much of database.

That's it. Now we're ready to be on the same page.

**Comment by calo1** [comment]
Awesome Taek .. can you give us a summary of this during our meeting today?

**Comment by stlim0730** [comment]
I will -- actually, not a summary of it, but I want all of us to follow and finish this step on one's own laptop.
Further steps to come as separate issues. Welcome to refactoring bootcamp!
