### ISSUE TITLE
Update logos on contributions page - and personnel

### ISSUE THREAD

**Issue by calo1** [stlim0730/farmview#89]
Per contract Big Ideas Logo needs to be included.  CartoDB needs to be changed to CARTO.  Current people should get a picture. past people just get Name, title and link if appropriate.  Taek's needs to change to Cornell?

**Comment by calo1** [comment]
Once the css appears karin can make a pull request on her branch

**Comment by stlim0730** [comment]
Yes. Please use the info and photo below as you update the bio page.

```
PhD Student, Cornell University
```

I finally have my photo with _SMALLER HEAD_.
```
https://stlim0730.github.io/img/profile_new.jpg
```

Thanks!

**Comment by calo1** [comment]
Are you holding that canoe paddle correctly?

**Comment by stlim0730** [comment]
Yes, I was. Lol
Not in the photo, though. The photo was a sudden capture by my bro in law.
How dare you doubt the _captain_ at the back seat of the boat as an experienced paddler!

**Comment by calo1** [comment]
All that needs to happen is @stlim0730  to update the production server on heroku

**Comment by stlim0730** [comment]
@calo1, create an account on [Heroku](https://www.heroku.com) and let me know.
Then, I'll add you as a collaborator with the deployment permission.

**Comment by karingoh** [comment]
Fixed and deployed!
