### ISSUE TITLE
Formspree failure: About page contact form is broken

### ISSUE THREAD

**Issue by calo1** [stlim0730/farmview#90]
error was : could not find referrer header.

**Comment by karingoh** [comment]
https://stackoverflow.com/questions/36380051/why-is-my-browser-not-sending-any-referrer

**Comment by calo1** [comment]
is this resolved?

**Comment by stlim0730** [comment]
I don't understand the issue. Further description's required.

**Comment by calo1** [comment]
We will test this again today and see if it needs any repair.  Low priority

**Comment by calo1** [comment]
resolved as long there a real email
