### ISSUE TITLE
Mapbook maps are missing data

### ISSUE THREAD

**Issue by calo1** [stlim0730/farmview#91]
This is most likely because Carto was updated.  Recheck privacy settings and publishing settings and see if mapbook reflects changes

**Comment by calo1** [comment]
Editing and republishing made the problem worse.  Map has console errors pulling data.  Emailing CARTO support with errors.

**Comment by calo1** [comment]
Actually what happened:  when Cartodb went to CARTO all datasets went private.  Need to remake those published public and review legend styles.

**Comment by karingoh** [comment]
Adam has one more map to fix
